In [2]:
#Import modules
import os
import csv
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib import style
import seaborn as sns
%matplotlib inline

#Create callable path to files
csvpath1 = os.path.join("data","ACS_14_1YR_S1901_with_ann.csv")
csvpath2 = os.path.join("data","BRFSS_2014_overall.csv")

In [3]:
style.use('seaborn-dark')

In [4]:
income = pd.read_csv(csvpath1)
education = pd.read_csv(csvpath2)

In [5]:
income

,GEO.id,GEO.id2,GEO.display-label,HC01_EST_VC01,HC01_MOE_VC01,HC02_EST_VC01,HC02_MOE_VC01,HC03_EST_VC01,HC03_MOE_VC01,HC04_EST_VC01,...,HC02_MOE_VC15,HC03_EST_VC15,HC03_MOE_VC15,HC04_EST_VC15,HC04_MOE_VC15,HC01_EST_VC18,HC01_MOE_VC18,HC02_EST_VC18,HC02_MOE_VC18,HC03_EST_VC18
0,Id,Id2,Geography,Households; Estimate; Total,Households; Margin of Error; Total,Families; Estimate; Total,Families; Margin of Error; Total,Married-couple families; Estimate; Total,Married-couple families; Margin of Error; Total,Nonfamily households; Estimate; Total,...,Families; Margin of Error; Mean income (dollars),Married-couple families; Estimate; Mean income...,Married-couple families; Margin of Error; Mean...,Nonfamily households; Estimate; Mean income (d...,Nonfamily households; Margin of Error; Mean in...,Households; Estimate; PERCENT IMPUTED - Househ...,Households; Margin of Error; PERCENT IMPUTED -...,Families; Estimate; PERCENT IMPUTED - Househol...,Families; Margin of Error; PERCENT IMPUTED - H...,Married-couple families; Estimate; PERCENT IMP...
1,0400000US01,1,Alabama,1841217,10615,1232515,11755,870026,12061,608702,...,924,85551,1247,34398,711,34.2,(X),(X),(X),(X)
2,0400000US02,2,Alaska,249659,2978,165015,3765,124028,3565,84644,...,2717,112794,3303,64015,3636,28.9,(X),(X),(X),(X)
3,0400000US04,4,Arizona,2428743,11353,1579481,13962,1141295,13485,849262,...,963,91238,1177,45085,913,32.7,(X),(X),(X),(X)
4,0400000US05,5,Arkansas,1131288,8373,752212,9854,546528,9376,379076,...,1546,80040,1938,34464,1056,29.3,(X),(X),(X),(X)
5,0400000US06,6,California,12758648,18835,8762059,27318,6239143,26454,3996589,...,466,116065,682,61229,512,32.6,(X),(X),(X),(X)
6,0400000US08,8,Colorado,2039592,7530,1315283,8405,1005726,10270,724309,...,1273,110103,1567,52518,1065,28.3,(X),(X),(X),(X)
7,0400000US09,9,Connecticut,1355817,6673,887263,10002,650673,9276,468554,...,1752,144134,2168,57595,1967,31.9,(X),(X),(X),(X)
8,0400000US10,10,Delaware,349743,3705,233000,4645,165362,4195,116743,...,2862,106106,3284,50877,2499,37.7,(X),(X),(X),(X)
9,0400000US11,11,District of Columbia,277378,3304,117864,3359,66244,3097,159514,...,4501,178408,7370,84957,3738,30.5,(X),(X),(X),(X)
10,0400000US12,12,Florida,7328046,25793,4693411,24879,3380103,24537,2634635,...,626,92538,817,43989,502,34,(X),(X),(X),(X)
11,0400000US13,13,Georgia,3587521,13961,2426392,15122,1692033,16406,1161129,...,807,95862,1017,43557,816,33.2,(X),(X),(X),(X)
12,0400000US15,15,Hawaii,450769,4870,314151,5725,232049,4639,136618,...,2353,107596,2877,55586,2365,31.4,(X),(X),(X),(X)
13,0400000US16,16,Idaho,591587,4733,407499,5941,324619,6464,184088,...,2144,82828,2383,38448,2309,30.6,(X),(X),(X),(X)
14,0400000US17,17,Illinois,4772421,12392,3099184,17994,2269298,16848,1673237,...,843,110525,1031,48899,578,32.4,(X),(X),(X),(X)
15,0400000US18,18,Indiana,2502739,10912,1657223,12597,1219395,13717,845516,...,791,88723,926,38554,695,28.2,(X),(X),(X),(X)
16,0400000US19,19,Iowa,1241471,6257,801562,6871,636747,7680,439909,...,1272,94670,1445,40849,928,29.6,(X),(X),(X),(X)
17,0400000US20,20,Kansas,1109280,6429,728602,7887,564871,8163,380678,...,1281,97278,1597,41194,1285,28.2,(X),(X),(X),(X)
18,0400000US21,21,Kentucky,1712094,8632,1124586,10250,828926,10947,587508,...,897,82175,1019,35178,805,29.8,(X),(X),(X),(X)
19,0400000US22,22,Louisiana,1718194,10232,1112659,9882,741899,10099,605535,...,1106,93342,1441,38526,968,34.6,(X),(X),(X),(X)
20,0400000US23,23,Maine,549841,5205,344585,5357,263704,4972,205256,...,1782,89785,2304,41744,2597,24.8,(X),(X),(X),(X)
21,0400000US24,24,Maryland,2165438,8230,1445972,11686,1022058,12423,719466,...,1171,133334,1457,60494,1058,33,(X),(X),(X),(X)
22,0400000US25,25,Massachusetts,2549336,9145,1610581,11929,1183524,12258,938755,...,1157,136207,1492,58351,990,32.5,(X),(X),(X),(X)
23,0400000US26,26,Michigan,3834574,12574,2485159,14714,1814961,13892,1349415,...,623,93320,815,40684,537,29.9,(X),(X),(X),(X)
24,0400000US27,27,Minnesota,2129195,6975,1369594,10930,1075956,10727,759601,...,1040,111818,1226,47805,728,24.9,(X),(X),(X),(X)
25,0400000US28,28,Mississippi,1095823,8793,738463,9100,482221,9251,357360,...,1167,79997,1611,32150,1057,32.9,(X),(X),(X),(X)
26,0400000US29,29,Missouri,2354809,12290,1508816,13340,1124715,11111,845993,...,782,90315,833,39233,847,29.4,(X),(X),(X),(X)
27,0400000US30,30,Montana,410962,3391,251176,5144,199495,5288,159786,...,1590,84770,1798,39045,1635,31.4,(X),(X),(X),(X)
28,0400000US31,31,Nebraska,740765,3795,480317,5426,371696,5522,260448,...,1245,92195,1499,41499,1056,27.7,(X),(X),(X),(X)
29,0400000US32,32,Nevada,1021519,6553,642461,7985,447162,6558,379058,...,1386,88858,1838,46443,1318,33.6,(X),(X),(X),(X)
30,0400000US33,33,New Hampshire,519756,4605,345901,5099,270978,4490,173855,...,2041,114580,2364,53249,2207,26.7,(X),(X),(X),(X)
31,0400000US34,34,New Jersey,3194844,10719,2203675,15024,1607880,11979,991169,...,1145,135242,1479,58519,1114,34.6,(X),(X),(X),(X)
32,0400000US35,35,New Mexico,760916,6897,489532,7201,340733,6214,271384,...,1655,85403,2316,39844,1432,28.6,(X),(X),(X),(X)
33,0400000US36,36,New York,7282398,15877,4621954,18878,3176379,16778,2660444,...,905,122038,1190,57811,814,36.2,(X),(X),(X),(X)
34,0400000US37,37,North Carolina,3790620,14716,2492048,17217,1803874,15234,1298572,...,728,91052,985,40375,618,28.5,(X),(X),(X),(X)
35,0400000US38,38,North Dakota,305431,3533,187800,4204,149016,3686,117631,...,3070,108478,3265,47997,2766,29.5,(X),(X),(X),(X)
36,0400000US39,39,Ohio,4593172,13994,2923523,16690,2104719,15671,1669649,...,654,94548,800,40081,490,28.8,(X),(X),(X),(X)
37,0400000US40,40,Oklahoma,1459759,5575,966516,7153,710773,6030,493243,...,914,88707,1189,38853,757,32.5,(X),(X),(X),(X)
38,0400000US41,41,Oregon,1535511,6674,966250,10337,730615,9955,569261,...,1007,94235,1345,44143,949,25,(X),(X),(X),(X)
39,0400000US42,42,Pennsylvania,4945972,12878,3185054,17847,2364442,15878,1760918,...,648,101761,758,43846,543,30.8,(X),(X),(X),(X)
40,0400000US44,44,Rhode Island,409654,3327,257165,5063,179215,4972,152489,...,2049,109378,2733,50615,2926,33,(X),(X),(X),(X)
41,0400000US45,45,South Carolina,1826914,10151,1201616,11426,847329,10524,625298,...,960,87823,1148,38426,1198,31.4,(X),(X),(X),(X)
42,0400000US46,46,South Dakota,334475,2656,211235,4208,165729,4179,123240,...,2304,91646,2786,39841,2365,26.3,(X),(X),(X),(X)
43,0400000US47,47,Tennessee,2509665,11315,1660344,15866,1203038,14862,849321,...,959,87900,1154,37961,972,31.6,(X),(X),(X),(X)
44,0400000US48,48,Texas,9277197,22719,6407165,29321,4603234,27270,2870032,...,560,102091,728,48607,664,31.2,(X),(X),(X),(X)
45,0400000US49,49,Utah,918370,4666,691495,6211,566881,6427,226875,...,1229,94628,1294,46098,1770,27.6,(X),(X),(X),(X)
46,0400000US50,50,Vermont,257229,3177,162017,3119,125741,3293,95212,...,2649,95152,3219,44178,1822,26.6,(X),(X),(X),(X)
47,0400000US51,51,Virginia,3083820,12955,2058820,15546,1544439,14338,1025000,...,839,118479,1138,56794,859,30.1,(X),(X),(X),(X)
48,0400000US53,53,Washington,2679601,9916,1725099,12755,1329276,12459,954502,...,1042,107714,1299,52745,952,25.7,(X),(X),(X),(X)
49,0400000US54,54,West Virginia,735375,6298,472869,8027,355690,7517,262506,...,1150,75118,1501,33520,1297,32.3,(X),(X),(X),(X)
50,0400000US55,55,Wisconsin,2307685,7753,1485877,10597,1133193,10338,821808,...,936,94806,1092,41698,658,26.7,(X),(X),(X),(X)
51,0400000US56,56,Wyoming,232594,2987,149032,3982,117040,3830,83562,...,2666,95636,3448,45583,3649,32.8,(X),(X),(X),(X)
52,0400000US72,72,Puerto Rico,1233490,9061,867505,10682,489760,8473,365985,...,781,43125,1226,18687,795,27.6,(X),(X),(X),(X)

In [6]:
education

,Year,Locationabbr,Response,Sample_Size,Data_value,Confidence_limit_Low,Confidence_limit_High
0,2014,AL,Less than H.S.,"1,063",17.4,16.1,18.7
1,2014,AL,H.S. or G.E.D.,"2,756",31.0,29.6,32.4
2,2014,AL,Some post-H.S.,"2,470",31.2,29.8,32.6
3,2014,AL,College+,"2,327",20.4,19.4,21.5
4,2014,AK,Less than H.S.,232,9.7,8.1,11.2
5,2014,AK,H.S. or G.E.D.,"1,119",28.3,26.4,30.2
6,2014,AK,Some post-H.S.,"1,289",37.9,35.8,40.0
7,2014,AK,College+,"1,706",24.1,22.6,25.6
8,2014,AZ,Less than H.S.,"1,129",15.4,14.2,16.6
9,2014,AZ,H.S. or G.E.D.,"3,464",25.5,24.3,26.7
10,2014,AZ,Some post-H.S.,"4,417",35.2,33.9,36.5
11,2014,AZ,College+,"5,706",23.9,22.9,24.8
12,2014,AR,Less than H.S.,604,16.8,14.9,18.7
13,2014,AR,H.S. or G.E.D.,"1,860",35.0,33.0,37.1
14,2014,AR,Some post-H.S.,"1,391",30.0,28.0,32.0
15,2014,AR,College+,"1,347",18.2,16.9,19.6
16,2014,CA,Less than H.S.,"1,084",19.1,17.9,20.3
17,2014,CA,H.S. or G.E.D.,"1,585",21.8,20.6,22.9
18,2014,CA,Some post-H.S.,"2,230",31.9,30.6,33.2
19,2014,CA,College+,"3,680",27.3,26.2,28.4
20,2014,CO,Less than H.S.,767,10.8,9.9,11.7
21,2014,CO,H.S. or G.E.D.,"3,120",22.9,22.0,23.9
22,2014,CO,Some post-H.S.,"3,630",32.9,31.8,34.0
23,2014,CO,College+,"5,791",33.4,32.5,34.3
24,2014,CT,Less than H.S.,517,11.6,10.4,12.8
25,2014,CT,H.S. or G.E.D.,"1,837",27.9,26.5,29.4
26,2014,CT,Some post-H.S.,"1,742",27.6,26.1,29.1
27,2014,CT,College+,"3,777",32.9,31.5,34.2
28,2014,DE,Less than H.S.,401,13.4,11.7,15.0
29,2014,DE,H.S. or G.E.D.,"1,275",31.5,29.4,33.5
...,...,...,...,...,...,...,...
190,2014,WA,Some post-H.S.,"3,025",35.8,34.5,37.2
191,2014,WA,College+,"4,356",28.7,27.6,29.7
192,2014,WV,Less than H.S.,763,16.6,15.3,17.8
193,2014,WV,H.S. or G.E.D.,"2,370",40.2,38.7,41.7
194,2014,WV,Some post-H.S.,"1,523",26.6,25.2,28.0
195,2014,WV,College+,"1,519",16.6,15.7,17.6
196,2014,WI,Less than H.S.,386,10.3,8.9,11.6
197,2014,WI,H.S. or G.E.D.,"2,342",32.9,31.4,34.5
198,2014,WI,Some post-H.S.,"2,065",32.5,30.9,34.1
199,2014,WI,College+,"2,207",24.3,23.1,25.6
200,2014,WY,Less than H.S.,344,8.7,7.3,10.2
201,2014,WY,H.S. or G.E.D.,"1,900",30.2,28.2,32.2
202,2014,WY,Some post-H.S.,"1,949",38.2,36.1,40.4
203,2014,WY,College+,"2,170",22.8,21.3,24.3
204,2014,GU,Less than H.S.,232,21.4,18.4,24.4
205,2014,GU,H.S. or G.E.D.,909,34.7,32.2,37.2
206,2014,GU,Some post-H.S.,592,21.2,19.1,23.3
207,2014,GU,College+,765,22.7,20.8,24.7
208,2014,PR,Less than H.S.,"1,268",27.3,25.7,28.8
209,2014,PR,H.S. or G.E.D.,"1,495",26.6,25.1,28.0
210,2014,PR,Some post-H.S.,"1,464",16.7,15.7,17.8
211,2014,PR,College+,"1,737",29.4,28.0,30.9
212,2014,UW,Less than H.S.,51,12.2,NaN,NaN
213,2014,UW,H.S. or G.E.D.,51,29.4,NaN,NaN
214,2014,UW,Some post-H.S.,51,31.3,NaN,NaN
215,2014,UW,College+,51,24.7,NaN,NaN
216,2014,US,Less than H.S.,53,12.5,NaN,NaN
217,2014,US,H.S. or G.E.D.,53,29.4,NaN,NaN
218,2014,US,Some post-H.S.,53,31.2,NaN,NaN
219,2014,US,College+,53,24.7,NaN,NaN